version: 1
disable_existing_loggers: False
# 构建日志格式
formatters:
  simple:
    format: "%(asctime)s  File '%(filename)s',line %(lineno)s  %(levelname)s: %(message)s"
# 构建处理器
handlers:
  stream_hander:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: 'ext://sys.stdout'
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: log.txt
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
# 构建logger
loggers:
  test:
    level: DEBUG
    handlers: [stream_hander]
    propagate: no
# root logger
root:
  level: INFO
  handlers: [stream_hander, file_handler]