# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tensorTransfer_pb2 as tensorTransfer__pb2


class tensorTransferStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleMethod = channel.unary_unary(
                '/tensorTransfer.tensorTransfer/SimpleMethod',
                request_serializer=tensorTransfer__pb2.Request.SerializeToString,
                response_deserializer=tensorTransfer__pb2.Reponse.FromString,
                )


class tensorTransferServicer(object):
    """The greeting service definition.
    """

    def SimpleMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_tensorTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethod,
                    request_deserializer=tensorTransfer__pb2.Request.FromString,
                    response_serializer=tensorTransfer__pb2.Reponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorTransfer.tensorTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class tensorTransfer(object):
    """The greeting service definition.
    """

    @staticmethod
    def SimpleMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorTransfer.tensorTransfer/SimpleMethod',
            tensorTransfer__pb2.Request.SerializeToString,
            tensorTransfer__pb2.Reponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
